FROM node:20-alpine3.16

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

COPY packages ./packages
COPY apps ./apps

RUN npm install
RUN npm run build

CMD [ "npm","run","start-user-app"]